//! Screenshot annotation state machine, ported from
//! `apps/desktop/src/renderer/src/screenshot/screenshotState.ts` (types, initial
//! state, reducer, rect normalization, completion gating) with the text-prompt
//! lifecycle folded in from `ScreenshotOverlay.tsx`.
//!
//! Coordinates are logical screen points; the reducer itself is agnostic. The TS
//! overlay feeds it selection-local annotation points (`toSelectionPoint`), and
//! the Slint host is expected to do the same.
//!
//! Behavior notes and deliberate divergences from the TS source:
//!
//! * Undo/redo stacks are uncapped, matching TS. The M3 plan asked to check for
//!   a stack cap: `screenshotReducer` slices/pushes without any limit, so the
//!   port keeps `annotations`/`redo_annotations` unbounded.
//! * TS annotations carry no ids (`screenshotState.ts` never generates one).
//!   The Rust [`Annotation`] adds a `uuid` v4 `id` — generated by the reducer
//!   when a draft starts and when an annotation input is committed — so the
//!   Slint layer can key annotation elements. `AnnotationAdded` keeps the
//!   caller-supplied id verbatim.
//! * [`Tool::Translation`] mirrors the TS `'translation'` annotation variant,
//!   which sits outside `ScreenshotTool`. It is not user-selectable and only
//!   enters the state through [`ScreenshotAction::AnnotationAdded`] (translation
//!   overlays keep their own style instead of the active drawing style).
//! * [`ToolSelected`](ScreenshotAction::ToolSelected) does **not** discard an
//!   in-progress draft. The M3 brief expected tool switches to drop the draft,
//!   but the TS reducer only assigns `tool` (screenshotState.ts:202-206) and
//!   later updates keep mutating the draft by its own tool; the port stays
//!   TS-exact.
//! * `done`, `text_prompt`, and the `Complete`/`CommitText`/`Cancel`/`Reset`/
//!   `TextPromptStarted` actions are extensions. The TS overlay gated
//!   completion on `isScreenshotReadyToComplete` outside the reducer and kept
//!   the pending text annotation in React state; the Slint host needs both
//!   inside the reducer so no state logic lives in the UI layer.
//!   `TextPromptStarted` ports the text-tool pointer-up check
//!   `distance(start, end) <= 3` (ScreenshotOverlay.tsx) that opens the prompt,
//!   and `CommitText` ports `commitPendingTextAnnotation` (trim, skip empty,
//!   apply the current style, clear the redo stack like every commit).
//! * `Cancel` and `Reset` both return to [`initial_state`]; they exist for
//!   host readability (discard session vs. start a fresh capture). Whether the
//!   session was canceled is the caller's concern.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Maximum pointer travel for a text-tool press to count as a click and open
/// the text prompt. Mirrors `distance(start, end) <= 3` in `ScreenshotOverlay.tsx`.
pub const TEXT_PROMPT_MAX_DRAG_DISTANCE: f64 = 3.0;

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

/// Screenshot annotation tool. Serde names match the TS string literals
/// (`'rectangle' | 'ellipse' | 'arrow' | 'pen' | 'text' | 'mosaic'`).
///
/// [`Tool::Translation`] is a pseudo-tool for translation overlays only and is
/// never produced by [`ScreenshotAction::ToolSelected`] in the UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Tool {
    Rectangle,
    Ellipse,
    Arrow,
    Pen,
    Text,
    Mosaic,
    Translation,
}

impl Tool {
    /// Whether the toolbar may select this tool (translation overlays cannot).
    pub fn is_user_selectable(self) -> bool {
        !matches!(self, Self::Translation)
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AnnotationStyle {
    /// `#rrggbb`.
    pub color: String,
    pub font_size: f64,
    pub line_width: f64,
}

impl Default for AnnotationStyle {
    /// TS defaults from `createInitialScreenshotState` (screenshotState.ts:135-139).
    fn default() -> Self {
        Self {
            color: "#ff3355".to_string(),
            font_size: 18.0,
            line_width: 3.0,
        }
    }
}

/// One committed or in-progress annotation. Geometry is flattened into
/// `points` per tool (TS uses a tagged union):
///
/// * `rectangle` / `ellipse` / `mosaic` / `translation`: two corner points;
///   the effective rectangle is [`normalize_rect`] of the pair.
/// * `arrow`: exactly two points (from, to).
/// * `pen`: polyline with one or more points.
/// * `text`: a single anchor point plus [`Annotation::text`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Annotation {
    pub id: String,
    pub tool: Tool,
    pub style: AnnotationStyle,
    pub points: Vec<Point>,
    pub text: Option<String>,
}

/// An annotation to commit without style/id: the reducer applies the active
/// style and generates the id (TS `ScreenshotAnnotationInput` + `withStyle`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AnnotationInput {
    pub tool: Tool,
    pub points: Vec<Point>,
    pub text: Option<String>,
}

impl AnnotationInput {
    fn into_annotation(self, id: String, style: AnnotationStyle) -> Annotation {
        Annotation {
            id,
            tool: self.tool,
            style,
            points: self.points,
            text: self.text,
        }
    }
}

impl Annotation {
    /// Normalized rectangle for rect-like tools (rectangle/ellipse/mosaic/
    /// translation), mirroring the TS `rect` payload of those variants.
    pub fn rect(&self) -> Option<Rect> {
        match self.tool {
            Tool::Rectangle | Tool::Ellipse | Tool::Mosaic | Tool::Translation => {
                match self.points.as_slice() {
                    [from, to] => Some(normalize_rect(*from, *to)),
                    _ => None,
                }
            }
            _ => None,
        }
    }

    /// Arrow geometry (from, to), mirroring the TS `arrow` payload.
    pub fn from_to(&self) -> Option<(Point, Point)> {
        match self.tool {
            Tool::Arrow => match self.points.as_slice() {
                [from, to] => Some((*from, *to)),
                _ => None,
            },
            _ => None,
        }
    }

    /// TS `isCommittableAnnotation`: whether a draft may be committed on finish.
    pub fn is_committable(&self) -> bool {
        let visible_text = self
            .text
            .as_deref()
            .is_some_and(|text| !text.trim().is_empty());
        match self.tool {
            Tool::Rectangle | Tool::Ellipse | Tool::Mosaic => {
                self.rect().is_some_and(|rect| is_non_empty_rect(&rect))
            }
            // TS: from.x !== to.x || from.y !== to.y.
            Tool::Arrow => self.from_to().is_some_and(|(from, to)| from != to),
            Tool::Pen => self.points.len() > 1,
            Tool::Text => visible_text,
            Tool::Translation => {
                visible_text && self.rect().is_some_and(|rect| is_non_empty_rect(&rect))
            }
        }
    }
}

/// Pending text-tool input (TS `pendingTextAnnotation` React state).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TextPrompt {
    pub point: Point,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScreenshotState {
    pub annotation_anchor: Option<Point>,
    pub annotations: Vec<Annotation>,
    pub draft_annotation: Option<Annotation>,
    pub redo_annotations: Vec<Annotation>,
    pub selection: Option<Rect>,
    pub selection_anchor: Option<Point>,
    pub style: AnnotationStyle,
    pub tool: Tool,
    /// Set by [`ScreenshotAction::Complete`] only when ready to complete.
    /// A new selection (`SelectionStarted`/`SelectionSet`) clears it again.
    pub done: bool,
    /// Pending text-tool input, if any.
    pub text_prompt: Option<TextPrompt>,
}

/// Reducer actions; serde variant names match the TS action `type` literals.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum ScreenshotAction {
    SelectionStarted {
        point: Point,
    },
    SelectionUpdated {
        point: Point,
    },
    SelectionEnded,
    SelectionSet {
        rect: Rect,
    },
    ToolSelected {
        tool: Tool,
    },
    ColorSelected {
        color: String,
    },
    #[serde(rename_all = "camelCase")]
    LineWidthSelected {
        line_width: f64,
    },
    #[serde(rename_all = "camelCase")]
    FontSizeSelected {
        font_size: f64,
    },
    AnnotationCommitted {
        annotation: AnnotationInput,
    },
    AnnotationAdded {
        annotation: Annotation,
    },
    AnnotationStarted {
        point: Point,
    },
    AnnotationUpdated {
        point: Point,
    },
    AnnotationFinished,
    AnnotationCanceled,
    /// Text-tool pointer-up: opens the text prompt when the gesture traveled
    /// at most [`TEXT_PROMPT_MAX_DRAG_DISTANCE`], otherwise cancels the draft.
    #[serde(rename_all = "camelCase")]
    TextPromptStarted {
        from: Point,
        to: Point,
    },
    /// Commit (or discard when blank) the pending text prompt.
    CommitText {
        value: String,
    },
    Undo,
    Redo,
    Complete,
    Cancel,
    Reset,
}

pub fn initial_state() -> ScreenshotState {
    ScreenshotState {
        annotation_anchor: None,
        annotations: Vec::new(),
        draft_annotation: None,
        redo_annotations: Vec::new(),
        selection: None,
        selection_anchor: None,
        style: AnnotationStyle::default(),
        tool: Tool::Rectangle,
        done: false,
        text_prompt: None,
    }
}

/// TS `normalizeScreenshotRect`: top-left corner plus absolute extents, so
/// negative drags yield positive width/height.
pub fn normalize_rect(from: Point, to: Point) -> Rect {
    Rect {
        x: from.x.min(to.x),
        y: from.y.min(to.y),
        width: (to.x - from.x).abs(),
        height: (to.y - from.y).abs(),
    }
}

/// TS `normalizePositiveRect`: re-normalizes a rect given as one corner plus a
/// signed size (used by `selection-set`).
fn normalize_positive_rect(rect: Rect) -> Rect {
    normalize_rect(
        Point {
            x: rect.x,
            y: rect.y,
        },
        Point {
            x: rect.x + rect.width,
            y: rect.y + rect.height,
        },
    )
}

/// TS `isNonEmptyScreenshotRect` (non-optional half; callers match on `Option`).
pub fn is_non_empty_rect(rect: &Rect) -> bool {
    rect.width > 0.0 && rect.height > 0.0
}

/// TS `isScreenshotReadyToComplete`.
pub fn is_ready_to_complete(state: &ScreenshotState) -> bool {
    state.selection.as_ref().is_some_and(is_non_empty_rect)
}

/// TS `distance` helper in `ScreenshotOverlay.tsx` (`Math.hypot`).
fn distance(from: Point, to: Point) -> f64 {
    let dx = to.x - from.x;
    let dy = to.y - from.y;
    (dx * dx + dy * dy).sqrt()
}

pub fn reducer(state: &ScreenshotState, action: ScreenshotAction) -> ScreenshotState {
    match action {
        ScreenshotAction::SelectionStarted { point } => ScreenshotState {
            annotation_anchor: None,
            annotations: Vec::new(),
            draft_annotation: None,
            redo_annotations: Vec::new(),
            selection: Some(Rect {
                x: point.x,
                y: point.y,
                width: 0.0,
                height: 0.0,
            }),
            selection_anchor: Some(point),
            // Extension: a new selection round invalidates a previous `done`.
            done: false,
            ..state.clone()
        },
        ScreenshotAction::SelectionUpdated { point } => {
            let anchor = state.selection_anchor.unwrap_or(point);
            ScreenshotState {
                selection: Some(normalize_rect(anchor, point)),
                ..state.clone()
            }
        }
        ScreenshotAction::SelectionEnded => ScreenshotState {
            selection_anchor: None,
            ..state.clone()
        },
        ScreenshotAction::SelectionSet { rect } => ScreenshotState {
            annotation_anchor: None,
            annotations: Vec::new(),
            draft_annotation: None,
            redo_annotations: Vec::new(),
            selection: Some(normalize_positive_rect(rect)),
            selection_anchor: None,
            done: false,
            ..state.clone()
        },
        ScreenshotAction::ToolSelected { tool } => ScreenshotState {
            tool,
            ..state.clone()
        },
        ScreenshotAction::ColorSelected { color } => ScreenshotState {
            style: AnnotationStyle {
                color,
                ..state.style.clone()
            },
            ..state.clone()
        },
        ScreenshotAction::LineWidthSelected { line_width } => ScreenshotState {
            style: AnnotationStyle {
                line_width,
                ..state.style.clone()
            },
            ..state.clone()
        },
        ScreenshotAction::FontSizeSelected { font_size } => ScreenshotState {
            style: AnnotationStyle {
                font_size,
                ..state.style.clone()
            },
            ..state.clone()
        },
        ScreenshotAction::AnnotationCommitted { annotation } => {
            let mut annotations = state.annotations.clone();
            annotations
                .push(annotation.into_annotation(Uuid::new_v4().to_string(), state.style.clone()));
            ScreenshotState {
                annotation_anchor: None,
                annotations,
                draft_annotation: None,
                redo_annotations: Vec::new(),
                ..state.clone()
            }
        }
        ScreenshotAction::AnnotationAdded { annotation } => {
            let mut annotations = state.annotations.clone();
            annotations.push(annotation);
            ScreenshotState {
                annotation_anchor: None,
                annotations,
                draft_annotation: None,
                redo_annotations: Vec::new(),
                ..state.clone()
            }
        }
        ScreenshotAction::AnnotationStarted { point } => ScreenshotState {
            annotation_anchor: Some(point),
            draft_annotation: Some(create_draft_annotation(
                state.tool,
                point,
                point,
                &state.style,
            )),
            ..state.clone()
        },
        ScreenshotAction::AnnotationUpdated { point } => {
            match (state.annotation_anchor, state.draft_annotation.as_ref()) {
                (Some(anchor), Some(draft)) => ScreenshotState {
                    draft_annotation: Some(update_draft_annotation(
                        draft,
                        anchor,
                        point,
                        &state.style,
                    )),
                    ..state.clone()
                },
                // TS returns the state unchanged without an anchor or draft.
                _ => state.clone(),
            }
        }
        ScreenshotAction::AnnotationFinished => {
            match state.draft_annotation.as_ref() {
                Some(draft) if draft.is_committable() => {
                    let mut annotations = state.annotations.clone();
                    annotations.push(draft.clone());
                    ScreenshotState {
                        annotation_anchor: None,
                        annotations,
                        draft_annotation: None,
                        redo_annotations: Vec::new(),
                        ..state.clone()
                    }
                }
                // Not committable (or no draft): drop the gesture entirely.
                _ => ScreenshotState {
                    annotation_anchor: None,
                    draft_annotation: None,
                    ..state.clone()
                },
            }
        }
        ScreenshotAction::AnnotationCanceled => ScreenshotState {
            annotation_anchor: None,
            draft_annotation: None,
            // Extension: the prompt is reducer-owned, so canceling the current
            // input also discards it (TS overlay cancels its React-side pending
            // text on the same gestures).
            text_prompt: None,
            ..state.clone()
        },
        ScreenshotAction::TextPromptStarted { from, to } => {
            // TS text-tool pointer-up: dispatches `annotation-canceled`, then
            // opens the prompt only when the gesture was a click.
            let cleared = ScreenshotState {
                annotation_anchor: None,
                draft_annotation: None,
                ..state.clone()
            };
            if distance(from, to) <= TEXT_PROMPT_MAX_DRAG_DISTANCE {
                ScreenshotState {
                    text_prompt: Some(TextPrompt {
                        point: to,
                        value: String::new(),
                    }),
                    ..cleared
                }
            } else {
                cleared
            }
        }
        ScreenshotAction::CommitText { value } => {
            let Some(prompt) = state.text_prompt.as_ref() else {
                return state.clone();
            };
            let text = value.trim();
            if text.is_empty() {
                // TS `commitPendingTextAnnotation` always clears the pending
                // text; blank input is dropped without dispatching a commit.
                return ScreenshotState {
                    text_prompt: None,
                    ..state.clone()
                };
            }
            let mut annotations = state.annotations.clone();
            annotations.push(Annotation {
                id: Uuid::new_v4().to_string(),
                tool: Tool::Text,
                style: state.style.clone(),
                points: vec![prompt.point],
                text: Some(text.to_string()),
            });
            ScreenshotState {
                annotation_anchor: None,
                annotations,
                draft_annotation: None,
                redo_annotations: Vec::new(),
                text_prompt: None,
                ..state.clone()
            }
        }
        ScreenshotAction::Undo => {
            let Some(undone) = state.annotations.last() else {
                return state.clone();
            };
            let mut annotations = state.annotations.clone();
            annotations.pop();
            let mut redo_annotations = state.redo_annotations.clone();
            redo_annotations.insert(0, undone.clone());
            ScreenshotState {
                annotations,
                redo_annotations,
                ..state.clone()
            }
        }
        ScreenshotAction::Redo => {
            let Some(redone) = state.redo_annotations.first() else {
                return state.clone();
            };
            let mut annotations = state.annotations.clone();
            annotations.push(redone.clone());
            let redo_annotations = state.redo_annotations[1..].to_vec();
            ScreenshotState {
                annotations,
                redo_annotations,
                ..state.clone()
            }
        }
        ScreenshotAction::Complete => {
            if is_ready_to_complete(state) {
                ScreenshotState {
                    done: true,
                    ..state.clone()
                }
            } else {
                state.clone()
            }
        }
        // Both discard the session and return to a fresh state; whether the
        // session was canceled vs. restarted is the caller's concern.
        ScreenshotAction::Cancel | ScreenshotAction::Reset => initial_state(),
    }
}

/// TS `createDraftAnnotation`. `from` and `to` start equal; the draft stores
/// the corner points and normalizes on read (equivalent to the TS payloads).
fn create_draft_annotation(
    tool: Tool,
    from: Point,
    to: Point,
    style: &AnnotationStyle,
) -> Annotation {
    let (points, text) = match tool {
        Tool::Rectangle | Tool::Ellipse | Tool::Mosaic | Tool::Translation => {
            (vec![from, to], None)
        }
        Tool::Arrow => (vec![from, to], None),
        Tool::Pen => (vec![from], None),
        Tool::Text => (vec![from], None),
    };
    Annotation {
        id: Uuid::new_v4().to_string(),
        tool,
        style: style.clone(),
        points,
        text,
    }
}

/// TS `updateDraftAnnotation`. Rect-like tools re-anchor to the original
/// pointer-down anchor, pen appends, text keeps its point/text and follows the
/// current style, translation is returned unchanged.
fn update_draft_annotation(
    draft: &Annotation,
    from: Point,
    to: Point,
    style: &AnnotationStyle,
) -> Annotation {
    let mut updated = draft.clone();
    updated.style = style.clone();
    match draft.tool {
        Tool::Rectangle | Tool::Ellipse | Tool::Mosaic | Tool::Translation => {
            updated.points = vec![from, to];
        }
        Tool::Arrow => {
            updated.points = vec![from, to];
        }
        Tool::Pen => {
            updated.points.push(to);
        }
        // Text drafts stay anchored at the pointer-down point, matching TS.
        Tool::Text => {}
    }
    updated
}

#[cfg(test)]
mod tests {
    use super::*;

    fn point(x: f64, y: f64) -> Point {
        Point { x, y }
    }

    fn rect(x: f64, y: f64, width: f64, height: f64) -> Rect {
        Rect {
            x,
            y,
            width,
            height,
        }
    }

    /// Annotation geometry in TS-shape order for rect-like tools: corners.
    fn corners(x: f64, y: f64, width: f64, height: f64) -> Vec<Point> {
        vec![point(x, y), point(x + width, y + height)]
    }

    fn input(tool: Tool, points: Vec<Point>, text: Option<&str>) -> AnnotationInput {
        AnnotationInput {
            tool,
            points,
            text: text.map(str::to_string),
        }
    }

    fn commit(annotation: AnnotationInput) -> ScreenshotAction {
        ScreenshotAction::AnnotationCommitted { annotation }
    }

    fn set_selection() -> ScreenshotAction {
        ScreenshotAction::SelectionSet {
            rect: rect(10.0, 20.0, 120.0, 90.0),
        }
    }

    #[test]
    fn initial_state_matches_ts_defaults() {
        let state = initial_state();
        assert_eq!(state.annotation_anchor, None);
        assert!(state.annotations.is_empty());
        assert_eq!(state.draft_annotation, None);
        assert!(state.redo_annotations.is_empty());
        assert_eq!(state.selection, None);
        assert_eq!(state.selection_anchor, None);
        assert_eq!(
            state.style,
            AnnotationStyle {
                color: "#ff3355".to_string(),
                font_size: 18.0,
                line_width: 3.0,
            }
        );
        assert_eq!(state.tool, Tool::Rectangle);
        assert!(!state.done);
        assert_eq!(state.text_prompt, None);
    }

    #[test]
    fn normalizes_selection_rectangles_from_negative_drags() {
        let state = reducer(
            &reducer(
                &initial_state(),
                ScreenshotAction::SelectionStarted {
                    point: point(120.0, 80.0),
                },
            ),
            ScreenshotAction::SelectionUpdated {
                point: point(20.0, 30.0),
            },
        );

        assert_eq!(state.selection, Some(rect(20.0, 30.0, 100.0, 50.0)));
        assert!(is_ready_to_complete(&state));
    }

    #[test]
    fn ready_to_complete_matrix() {
        let none = initial_state();
        assert!(!is_ready_to_complete(&none));

        let started = reducer(
            &none,
            ScreenshotAction::SelectionStarted {
                point: point(10.0, 10.0),
            },
        );
        assert_eq!(started.selection, Some(rect(10.0, 10.0, 0.0, 0.0)));
        assert!(!is_ready_to_complete(&started));

        let flat_width = reducer(
            &started,
            ScreenshotAction::SelectionUpdated {
                point: point(30.0, 10.0),
            },
        );
        assert!(!is_non_empty_rect(
            flat_width.selection.as_ref().expect("selection")
        ));
        assert!(!is_ready_to_complete(&flat_width));

        let flat_height = reducer(
            &started,
            ScreenshotAction::SelectionUpdated {
                point: point(10.0, 30.0),
            },
        );
        assert!(!is_ready_to_complete(&flat_height));

        let real = reducer(
            &started,
            ScreenshotAction::SelectionUpdated {
                point: point(30.0, 30.0),
            },
        );
        assert!(is_ready_to_complete(&real));
    }

    #[test]
    fn selects_annotation_tools_and_styles() {
        let actions = [
            ScreenshotAction::ToolSelected {
                tool: Tool::Ellipse,
            },
            ScreenshotAction::ColorSelected {
                color: "#ff3355".to_string(),
            },
            ScreenshotAction::LineWidthSelected { line_width: 6.0 },
            ScreenshotAction::FontSizeSelected { font_size: 24.0 },
        ];
        let mut state = initial_state();
        for action in actions {
            state = reducer(&state, action);
        }

        assert_eq!(state.tool, Tool::Ellipse);
        assert_eq!(
            state.style,
            AnnotationStyle {
                color: "#ff3355".to_string(),
                font_size: 24.0,
                line_width: 6.0,
            }
        );
    }

    #[test]
    fn commits_all_annotation_types_without_object_level_edit_state() {
        let selected = reducer(&initial_state(), set_selection());
        let inputs = [
            input(Tool::Rectangle, corners(12.0, 24.0, 40.0, 30.0), None),
            input(Tool::Ellipse, corners(14.0, 26.0, 40.0, 30.0), None),
            input(
                Tool::Arrow,
                vec![point(20.0, 30.0), point(80.0, 60.0)],
                None,
            ),
            input(Tool::Pen, vec![point(25.0, 35.0), point(35.0, 45.0)], None),
            input(Tool::Text, vec![point(30.0, 42.0)], Some("Note")),
            input(Tool::Mosaic, corners(40.0, 50.0, 24.0, 18.0), None),
        ];

        let mut state = selected;
        for annotation in inputs {
            state = reducer(&state, commit(annotation));
        }

        assert_eq!(state.annotations.len(), 6);
        assert_eq!(state.draft_annotation, None);
        let tools: Vec<Tool> = state.annotations.iter().map(|a| a.tool).collect();
        assert_eq!(
            tools,
            [
                Tool::Rectangle,
                Tool::Ellipse,
                Tool::Arrow,
                Tool::Pen,
                Tool::Text,
                Tool::Mosaic
            ]
        );
        // Every commit applies the active style.
        assert!(state
            .annotations
            .iter()
            .all(|a| a.style == initial_state().style));
    }

    #[test]
    fn supports_undo_redo_and_clears_redo_after_a_new_annotation() {
        let selected = reducer(&initial_state(), set_selection());
        let with_two = reducer(
            &reducer(
                &selected,
                commit(input(
                    Tool::Rectangle,
                    corners(12.0, 24.0, 10.0, 10.0),
                    None,
                )),
            ),
            commit(input(Tool::Mosaic, corners(30.0, 34.0, 16.0, 14.0), None)),
        );

        let undone = reducer(&with_two, ScreenshotAction::Undo);
        let redone = reducer(&undone, ScreenshotAction::Redo);
        let branched = reducer(
            &undone,
            commit(input(Tool::Text, vec![point(30.0, 42.0)], Some("New"))),
        );

        assert_eq!(undone.annotations.len(), 1);
        assert_eq!(undone.redo_annotations.len(), 1);
        assert_eq!(redone.annotations.len(), 2);
        let branched_tools: Vec<Tool> = branched.annotations.iter().map(|a| a.tool).collect();
        assert_eq!(branched_tools, [Tool::Rectangle, Tool::Text]);
        assert!(branched.redo_annotations.is_empty());
    }

    #[test]
    fn undo_and_redo_are_noops_on_empty_stacks() {
        let empty = initial_state();
        assert_eq!(reducer(&empty, ScreenshotAction::Undo), empty);
        assert_eq!(reducer(&empty, ScreenshotAction::Redo), empty);

        let after_undo_all = reducer(
            &reducer(
                &reducer(&initial_state(), set_selection()),
                commit(input(Tool::Rectangle, corners(1.0, 2.0, 3.0, 4.0), None)),
            ),
            ScreenshotAction::Undo,
        );
        assert!(after_undo_all.annotations.is_empty());
        assert_eq!(
            reducer(&after_undo_all, ScreenshotAction::Undo),
            after_undo_all
        );
    }

    #[test]
    fn adds_generated_translation_overlays_without_inheriting_the_active_style() {
        let selected = reducer(
            &reducer(
                &initial_state(),
                ScreenshotAction::ColorSelected {
                    color: "#ff3355".to_string(),
                },
            ),
            set_selection(),
        );
        let translation = Annotation {
            id: "translation-1".to_string(),
            tool: Tool::Translation,
            style: AnnotationStyle {
                color: "#111827".to_string(),
                font_size: 18.0,
                line_width: 1.0,
            },
            points: corners(0.0, 0.0, 24.0, 18.0),
            text: Some("Translation".to_string()),
        };

        let state = reducer(
            &selected,
            ScreenshotAction::AnnotationAdded {
                annotation: translation.clone(),
            },
        );

        assert_eq!(state.annotations, vec![translation]);
        assert!(state.redo_annotations.is_empty());
    }

    #[test]
    fn builds_and_commits_drag_rectangle_annotations_as_drafts() {
        let selected = reducer(
            &reducer(&initial_state(), set_selection()),
            ScreenshotAction::ToolSelected {
                tool: Tool::Rectangle,
            },
        );
        let drafting = reducer(
            &reducer(
                &selected,
                ScreenshotAction::AnnotationStarted {
                    point: point(80.0, 60.0),
                },
            ),
            ScreenshotAction::AnnotationUpdated {
                point: point(20.0, 25.0),
            },
        );
        let committed = reducer(&drafting, ScreenshotAction::AnnotationFinished);

        let draft = drafting.draft_annotation.as_ref().expect("draft");
        assert_eq!(draft.tool, Tool::Rectangle);
        assert_eq!(draft.rect(), Some(rect(20.0, 25.0, 60.0, 35.0)));
        assert_eq!(committed.annotations.len(), 1);
        assert_eq!(committed.draft_annotation, None);
        assert_eq!(committed.annotation_anchor, None);
    }

    #[test]
    fn builds_arrow_and_pen_annotations_from_drag_movement() {
        let selected = reducer(&initial_state(), set_selection());
        let arrow = reducer(
            &reducer(
                &reducer(
                    &selected,
                    ScreenshotAction::ToolSelected { tool: Tool::Arrow },
                ),
                ScreenshotAction::AnnotationStarted {
                    point: point(8.0, 12.0),
                },
            ),
            ScreenshotAction::AnnotationUpdated {
                point: point(48.0, 52.0),
            },
        );
        let pen = [
            ScreenshotAction::AnnotationStarted {
                point: point(5.0, 8.0),
            },
            ScreenshotAction::AnnotationUpdated {
                point: point(9.0, 11.0),
            },
            ScreenshotAction::AnnotationUpdated {
                point: point(15.0, 18.0),
            },
        ]
        .iter()
        .fold(
            reducer(
                &selected,
                ScreenshotAction::ToolSelected { tool: Tool::Pen },
            ),
            |state, action| reducer(&state, action.clone()),
        );

        let arrow_draft = arrow.draft_annotation.as_ref().expect("arrow draft");
        assert_eq!(arrow_draft.tool, Tool::Arrow);
        assert_eq!(
            arrow_draft.from_to(),
            Some((point(8.0, 12.0), point(48.0, 52.0)))
        );

        let pen_draft = pen.draft_annotation.as_ref().expect("pen draft");
        assert_eq!(pen_draft.tool, Tool::Pen);
        assert_eq!(
            pen_draft.points,
            vec![point(5.0, 8.0), point(9.0, 11.0), point(15.0, 18.0)]
        );
    }

    #[test]
    fn clears_selection_local_annotations_drafts_and_redo_when_selection_changes() {
        let selected = reducer(&initial_state(), set_selection());
        let annotated = reducer(
            &reducer(
                &selected,
                commit(input(Tool::Rectangle, corners(2.0, 4.0, 14.0, 10.0), None)),
            ),
            ScreenshotAction::AnnotationStarted {
                point: point(8.0, 12.0),
            },
        );
        let undone = reducer(&annotated, ScreenshotAction::Undo);
        let reset_by_start = reducer(
            &undone,
            ScreenshotAction::SelectionStarted {
                point: point(40.0, 50.0),
            },
        );
        let reset_by_set = reducer(
            &undone,
            ScreenshotAction::SelectionSet {
                rect: rect(1.0, 2.0, 30.0, 20.0),
            },
        );

        for state in [&reset_by_start, &reset_by_set] {
            assert!(state.annotations.is_empty());
            assert_eq!(state.draft_annotation, None);
            assert!(state.redo_annotations.is_empty());
        }
        assert_eq!(reset_by_start.selection, Some(rect(40.0, 50.0, 0.0, 0.0)));
        assert_eq!(reset_by_set.selection, Some(rect(1.0, 2.0, 30.0, 20.0)));
    }

    #[test]
    fn normalize_rect_handles_negative_dimensions() {
        assert_eq!(
            normalize_rect(point(120.0, 80.0), point(20.0, 30.0)),
            rect(20.0, 30.0, 100.0, 50.0)
        );
        assert_eq!(
            normalize_rect(point(20.0, 30.0), point(120.0, 80.0)),
            rect(20.0, 30.0, 100.0, 50.0)
        );
        assert_eq!(
            normalize_rect(point(5.0, 5.0), point(5.0, 5.0)),
            rect(5.0, 5.0, 0.0, 0.0)
        );
    }

    #[test]
    fn selection_set_normalizes_negative_width_height() {
        let state = reducer(
            &initial_state(),
            ScreenshotAction::SelectionSet {
                rect: rect(20.0, 30.0, -100.0, -50.0),
            },
        );
        assert_eq!(state.selection, Some(rect(-80.0, -20.0, 100.0, 50.0)));
        assert_eq!(state.selection_anchor, None);
        assert!(is_ready_to_complete(&state));
    }

    #[test]
    fn text_prompt_commit_and_cancel() {
        let selected = reducer(
            &reducer(&initial_state(), set_selection()),
            ScreenshotAction::ToolSelected { tool: Tool::Text },
        );
        let start = ScreenshotAction::AnnotationStarted {
            point: point(30.0, 42.0),
        };
        // A click (drag distance <= 3) opens the prompt.
        let prompted = reducer(
            &reducer(&selected, start),
            ScreenshotAction::TextPromptStarted {
                from: point(30.0, 42.0),
                to: point(32.0, 43.0),
            },
        );
        let prompt = prompted.text_prompt.as_ref().expect("prompt");
        assert_eq!(prompt.point, point(32.0, 43.0));
        assert_eq!(prompt.value, "");
        assert_eq!(prompted.draft_annotation, None);
        assert_eq!(prompted.annotation_anchor, None);

        let committed = reducer(
            &prompted,
            ScreenshotAction::CommitText {
                value: "  Note  ".to_string(),
            },
        );
        assert_eq!(committed.text_prompt, None);
        assert_eq!(committed.annotations.len(), 1);
        assert!(committed.redo_annotations.is_empty());
        let text = &committed.annotations[0];
        assert_eq!(text.tool, Tool::Text);
        assert_eq!(text.text.as_deref(), Some("Note"));
        assert_eq!(text.points, vec![point(32.0, 43.0)]);
        assert_eq!(text.style, prompted.style);
        assert!(!text.id.is_empty());

        // Blank input is discarded, matching commitPendingTextAnnotation.
        let blank = reducer(
            &prompted,
            ScreenshotAction::CommitText {
                value: "   ".to_string(),
            },
        );
        assert_eq!(blank.annotations.len(), 0);
        assert_eq!(blank.text_prompt, None);

        // CommitText without a prompt is a no-op.
        assert_eq!(
            reducer(
                &selected,
                ScreenshotAction::CommitText {
                    value: "x".to_string()
                }
            ),
            selected
        );
    }

    #[test]
    fn text_prompt_ignores_drags_beyond_click_threshold() {
        let selected = reducer(
            &reducer(&initial_state(), set_selection()),
            ScreenshotAction::ToolSelected { tool: Tool::Text },
        );
        let dragged = reducer(
            &reducer(
                &reducer(
                    &selected,
                    ScreenshotAction::AnnotationStarted {
                        point: point(10.0, 10.0),
                    },
                ),
                ScreenshotAction::TextPromptStarted {
                    from: point(10.0, 10.0),
                    to: point(20.0, 10.0),
                },
            ),
            ScreenshotAction::AnnotationFinished,
        );
        assert_eq!(dragged.text_prompt, None);
        assert_eq!(dragged.draft_annotation, None);
        assert!(dragged.annotations.is_empty());
    }

    #[test]
    fn annotation_finished_discards_non_committable_drafts() {
        let selected = reducer(&initial_state(), set_selection());

        let zero_rect = [
            ScreenshotAction::ToolSelected {
                tool: Tool::Rectangle,
            },
            ScreenshotAction::AnnotationStarted {
                point: point(5.0, 5.0),
            },
        ]
        .iter()
        .fold(selected.clone(), |state, action| {
            reducer(&state, action.clone())
        });
        let discarded = reducer(&zero_rect, ScreenshotAction::AnnotationFinished);
        assert!(discarded.annotations.is_empty());
        assert_eq!(discarded.draft_annotation, None);

        let single_point_pen = [
            ScreenshotAction::ToolSelected { tool: Tool::Pen },
            ScreenshotAction::AnnotationStarted {
                point: point(5.0, 5.0),
            },
        ]
        .iter()
        .fold(selected.clone(), |state, action| {
            reducer(&state, action.clone())
        });
        assert!(
            reducer(&single_point_pen, ScreenshotAction::AnnotationFinished)
                .annotations
                .is_empty()
        );

        let zero_arrow = [
            ScreenshotAction::ToolSelected { tool: Tool::Arrow },
            ScreenshotAction::AnnotationStarted {
                point: point(5.0, 5.0),
            },
        ]
        .iter()
        .fold(selected.clone(), |state, action| {
            reducer(&state, action.clone())
        });
        assert!(reducer(&zero_arrow, ScreenshotAction::AnnotationFinished)
            .annotations
            .is_empty());
    }

    #[test]
    fn annotation_updated_without_a_draft_is_a_noop() {
        let selected = reducer(&initial_state(), set_selection());
        assert_eq!(
            reducer(
                &selected,
                ScreenshotAction::AnnotationUpdated {
                    point: point(3.0, 4.0)
                },
            ),
            selected
        );
    }

    #[test]
    fn tool_switch_keeps_in_progress_draft_matching_ts() {
        // TS `tool-selected` only assigns `tool`; an in-progress draft survives
        // and keeps mutating as its original tool. Documented divergence from
        // the M3 brief, which expected the draft to be discarded.
        let drafting = reducer(
            &reducer(
                &reducer(&initial_state(), set_selection()),
                ScreenshotAction::AnnotationStarted {
                    point: point(10.0, 10.0),
                },
            ),
            ScreenshotAction::ToolSelected {
                tool: Tool::Ellipse,
            },
        );
        assert!(drafting.draft_annotation.is_some());
        assert_eq!(drafting.tool, Tool::Ellipse);

        let updated = reducer(
            &drafting,
            ScreenshotAction::AnnotationUpdated {
                point: point(30.0, 40.0),
            },
        );
        let draft = updated.draft_annotation.as_ref().expect("draft");
        // Still a rectangle draft even though the selected tool is now ellipse.
        assert_eq!(draft.tool, Tool::Rectangle);
        assert_eq!(draft.rect(), Some(rect(10.0, 10.0, 20.0, 30.0)));
    }

    #[test]
    fn complete_only_sets_done_when_ready() {
        let early = reducer(&initial_state(), ScreenshotAction::Complete);
        assert!(!early.done);

        let ready = reducer(&initial_state(), set_selection());
        let completed = reducer(&ready, ScreenshotAction::Complete);
        assert!(completed.done);
        // Completion keeps the selection for the export path.
        assert_eq!(completed.selection, ready.selection);

        // Completing again is stable.
        assert!(reducer(&completed, ScreenshotAction::Complete).done);

        // A new selection round clears the stale completion flag.
        let reselected = reducer(
            &completed,
            ScreenshotAction::SelectionStarted {
                point: point(1.0, 1.0),
            },
        );
        assert!(!reselected.done);
    }

    #[test]
    fn cancel_and_reset_return_to_initial_state() {
        let busy = reducer(
            &reducer(
                &reducer(&initial_state(), set_selection()),
                commit(input(Tool::Rectangle, corners(2.0, 4.0, 14.0, 10.0), None)),
            ),
            ScreenshotAction::Complete,
        );
        assert_eq!(reducer(&busy, ScreenshotAction::Cancel), initial_state());
        assert_eq!(reducer(&busy, ScreenshotAction::Reset), initial_state());
    }

    #[test]
    fn annotation_finished_without_a_draft_is_a_noop() {
        let selected = reducer(&initial_state(), set_selection());
        let finished = reducer(&selected, ScreenshotAction::AnnotationFinished);
        assert!(finished.annotations.is_empty());
        assert_eq!(finished.annotation_anchor, None);
    }

    #[test]
    fn committed_annotations_get_unique_uuid_ids() {
        let selected = reducer(&initial_state(), set_selection());
        let state = reducer(
            &reducer(
                &selected,
                commit(input(Tool::Rectangle, corners(2.0, 4.0, 14.0, 10.0), None)),
            ),
            commit(input(Tool::Rectangle, corners(6.0, 8.0, 14.0, 10.0), None)),
        );

        assert_eq!(state.annotations.len(), 2);
        for annotation in &state.annotations {
            assert_eq!(annotation.id.len(), 36, "uuid v4: {}", annotation.id);
        }
        assert_ne!(state.annotations[0].id, state.annotations[1].id);
    }

    #[test]
    fn is_committable_matches_ts_matrix() {
        let style = AnnotationStyle::default();
        let build = |tool: Tool, points: Vec<Point>, text: Option<&str>| Annotation {
            id: "id".to_string(),
            tool,
            style: style.clone(),
            points,
            text: text.map(str::to_string),
        };

        assert!(build(Tool::Rectangle, corners(0.0, 0.0, 1.0, 1.0), None).is_committable());
        assert!(!build(Tool::Rectangle, corners(0.0, 0.0, 0.0, 1.0), None).is_committable());
        assert!(!build(Tool::Ellipse, corners(0.0, 0.0, 1.0, 0.0), None).is_committable());
        assert!(!build(Tool::Mosaic, corners(0.0, 0.0, 0.0, 0.0), None).is_committable());
        // Fewer than two corners cannot form a rect.
        assert!(!build(Tool::Rectangle, vec![point(1.0, 1.0)], None).is_committable());

        assert!(build(Tool::Arrow, vec![point(0.0, 0.0), point(1.0, 1.0)], None).is_committable());
        assert!(!build(Tool::Arrow, vec![point(2.0, 3.0), point(2.0, 3.0)], None).is_committable());

        assert!(build(Tool::Pen, vec![point(0.0, 0.0), point(1.0, 1.0)], None).is_committable());
        assert!(!build(Tool::Pen, vec![point(0.0, 0.0)], None).is_committable());

        assert!(build(Tool::Text, vec![point(1.0, 1.0)], Some("hi")).is_committable());
        assert!(!build(Tool::Text, vec![point(1.0, 1.0)], Some("   ")).is_committable());
        assert!(!build(Tool::Text, vec![point(1.0, 1.0)], None).is_committable());

        assert!(build(Tool::Translation, corners(0.0, 0.0, 2.0, 2.0), Some("hi")).is_committable());
        assert!(
            !build(Tool::Translation, corners(0.0, 0.0, 0.0, 2.0), Some("hi")).is_committable()
        );
        assert!(!build(Tool::Translation, corners(0.0, 0.0, 2.0, 2.0), Some(" ")).is_committable());
    }

    #[test]
    fn translation_is_not_user_selectable() {
        for tool in [
            Tool::Rectangle,
            Tool::Ellipse,
            Tool::Arrow,
            Tool::Pen,
            Tool::Text,
            Tool::Mosaic,
        ] {
            assert!(tool.is_user_selectable());
        }
        assert!(!Tool::Translation.is_user_selectable());
    }

    #[test]
    fn tool_serializes_kebab_case_like_ts_literals() {
        for (tool, name) in [
            (Tool::Rectangle, "rectangle"),
            (Tool::Ellipse, "ellipse"),
            (Tool::Arrow, "arrow"),
            (Tool::Pen, "pen"),
            (Tool::Text, "text"),
            (Tool::Mosaic, "mosaic"),
            (Tool::Translation, "translation"),
        ] {
            let json = serde_json::to_string(&tool).expect("serialize");
            assert_eq!(json, format!("\"{name}\""));
            let back: Tool = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(back, tool);
        }
    }

    #[test]
    fn actions_and_annotations_round_trip_through_ts_shaped_json() {
        let action: ScreenshotAction =
            serde_json::from_str(r#"{"type":"line-width-selected","lineWidth":6}"#)
                .expect("deserialize action");
        assert_eq!(
            action,
            ScreenshotAction::LineWidthSelected { line_width: 6.0 }
        );

        let json = serde_json::to_string(&ScreenshotAction::TextPromptStarted {
            from: point(1.0, 2.0),
            to: point(3.0, 4.0),
        })
        .expect("serialize action");
        assert_eq!(
            json,
            r#"{"type":"text-prompt-started","from":{"x":1.0,"y":2.0},"to":{"x":3.0,"y":4.0}}"#
        );

        let annotation = Annotation {
            id: "abc".to_string(),
            tool: Tool::Rectangle,
            style: AnnotationStyle {
                color: "#ff3355".to_string(),
                font_size: 18.0,
                line_width: 3.0,
            },
            points: corners(0.0, 0.0, 2.0, 2.0),
            text: None,
        };
        let json = serde_json::to_string(&annotation).expect("serialize annotation");
        assert!(json.contains("\"fontSize\":18.0"));
        assert!(json.contains("\"lineWidth\":3.0"));
        let back: Annotation = serde_json::from_str(&json).expect("deserialize annotation");
        assert_eq!(back, annotation);
    }
}
